name: V8 Build Test

on:
  push:
    branches:
      - master
      - actions
    paths-ignore:
      - "depot_tools"
      - ".gitignore"
      - ".gitpod*"
  workflow_dispatch:

jobs:
  build-test-macos:
    name: Build V8
    strategy:
      matrix:
        os: [macos-13, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
          clean: true
          fetch-depth: 1
      - name: Restore V8 Cache
        uses: actions/cache@v4
        with:
          path: |
            v8
            .gclient_entries
            .gclient_previous_sync_commits
            .cipd
          key: ${{ runner.os }}-${{ runner.platform }}:libv8:v8:${{ hashFiles('**/VERSION') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.platform }}:libv8:v8:
      - name: Initialize Archive Name
        shell: bash
        run: ./.github/workflows/scripts/archive-name.sh
      - name: Build V8 for macOS (${{ runner.platform }})
        uses: ./.github/actions/build-macos
        with:
          archive-name: ${{ env.ARCHIVE_NAME }}
      - name: Archive V8 Library
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARCHIVE_NAME }}
          path: |
            *.tar.xz
            *.7z
          retention-days: 7

  build-test-linux-win:
    name: Build V8
    strategy:
      matrix:
        platform: [x64,arm64]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
          clean: true
          fetch-depth: 1

      - name: Restore V8 Cache
        uses: actions/cache@v4
        with:
          path: |
            v8
            .gclient_entries
            .gclient_previous_sync_commits
            .cipd
          key: ${{ runner.os }}-${{ runner.platform }}:libv8:v8:${{ hashFiles('**/VERSION') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.platform }}:libv8:v8:

      - name: Initialize Archive Name
        if: runner.os != 'Windows'
        shell: bash
        run: ./.github/workflows/scripts/archive-name.sh

      - name: Initialize Archive Name (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: .\.github\workflows\scripts\archive-name.ps1

      - name: Build V8 for Linux (${{ runner.platform }})
        if: startsWith(matrix.os, 'ubuntu')
        uses: ./.github/actions/build-linux
        with:
          archive-name: ${{ env.ARCHIVE_NAME }}

      - name: Build V8 for Windows
        if: startsWith(matrix.os, 'windows')
        uses: ./.github/actions/build-windows
        with:
          archive-name: ${{ env.ARCHIVE_NAME }}

      - name: Archive V8 Library
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARCHIVE_NAME }}
          path: |
            *.tar.xz
            *.7z
          retention-days: 7
